server:
  version: v1
  grpc:
    addr: 0.0.0.0:50052
    name: agentgo.base.agentService
    timeout: 1s
  http:
    addr: 0.0.0.0:8081
    timeout: 1s
data:
  database:
    driver: mysql
    source: lizq:ai5201314.@tcp(127.0.0.1:3306)/agentgo?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://127.0.0.1:14268/api/traces
